services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /containers/ollama:/root/.ollama

networks:
  default:
    enable_ipv6: true
