services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      ollama:
    volumes:
      - /containers/ollama:/root/.ollama

networks:
  ollama:
    name: ollama
    enable_ipv6: true
